### ISSUE TITLE
Is bowser.json and bower install required? 

### ISSUE THREAD

**Issue by schacki** [aldryn/aldryn-boilerplate-bootstrap3#164]
There is a bower.json file, it says in the docs that you should run bower install and there is a task that does install the bower dependencies. Based on the bowerrc file, the bower components are installed into "/static/vendor".

My first issue is that a normal user does not and should not have write permission for /static/vendor. I assume it should be "static/vendor".

And then I cannot find any references in the templates directory, where any files from the vendor directory are loaded. Instead it seems like a copy of the relevant files is stored as part of the repository in static/js/libs. So to me it looks like nothing of the installed bower modules is ever used. Is that correct?

**Comment by vxsx** [comment]
Hi @schacki 

first issue was fixed some time ago in this commit https://github.com/aldryn/aldryn-boilerplate-bootstrap3/commit/eeba6378bcd4c9fb64f507b96636f33b4eb35a62 and should be available in latest version

second - yes, we do not explicitly use anything in static/vendor in default installation, mostly because we don't want to force the user to some specific patterns. it is a user's choice to use or not to use bower entirely, in the end this is just the boilerplate

hope this helps
